map/urls.py
from django.conf.urls import include
from django.urls import path
from . import views

app_name = "map"
urlpatterns = [
    path("save_property/", views.save_property, name="save_property"),
    path("property_insert/", views.property_insert, name="property_insert"),
    
    path('<int:property>/', views.PropertyDetail.as_view(), name='property_detail'),
]

markers/urls.py
from django.urls import path, include
from rest_framework import routers
from markers.views import MarkersMapView, MarkerViewSet

app_name = "markers"

router = routers.DefaultRouter()
router.register(r"markers", MarkerViewSet)

urlpatterns = [
    path("api/", include(router.urls)),
    path("", MarkersMapView.as_view()),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from map import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home),
    path("map/", include("map.urls")),
    path(
        "markers/",
        include("markers.urls"),
    ),
]

map/models.py
from django.db import models
from django.contrib.gis.db import models as gismodels
# Create your models here.
class Property(models.Model):
    latlngs = models.JSONField(default = list)
    name = models.CharField(max_length=255)
    address = models.TextField()


class PropertyGIS(gismodels.Model):
    name = gismodels.CharField(max_length=255)
    GEOMETRY = gismodels.MultiPolygonField()

markers/models.py
from django.contrib.gis.db import models


class Lines(models.Model):
    ogc_fid = models.AutoField(primary_key=True, editable=False)
    osm_id = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    highway = models.CharField(max_length=255)
    waterway = models.CharField(max_length=255)
    aerialway = models.CharField(max_length=255)
    barrier = models.CharField(max_length=255)
    man_made = models.CharField(max_length=255)
    z_order = models.IntegerField()
    other_tags = models.CharField(max_length=255)
    GEOMETRY = models.LineStringField()
    class Meta:
        db_table = 'lines'
        managed = False

class MultilineStrings(models.Model):
    ogc_fid = models.AutoField(primary_key=True, editable=False)
    osm_id = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    type = models.CharField(max_length=255)
    other_tags = models.CharField(max_length=255)
    GEOMETRY = models.MultiLineStringField()

    class Meta:
        db_table = 'multilinestrings'
        managed = False


class MultiPolygons(models.Model):
    ogc_fid = models.AutoField(primary_key=True, editable=False)
    osm_id = models.CharField(max_length=255)
    osm_way_id = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    type = models.CharField(max_length=255)
    aeroway = models.CharField(max_length=255)
    amenity = models.CharField(max_length=255)
    admin_level = models.CharField(max_length=255)
    barrier = models.CharField(max_length=255)
    boundary = models.CharField(max_length=255)
    building = models.CharField(max_length=255)
    craft = models.CharField(max_length=255)
    geological = models.CharField(max_length=255)
    historic = models.CharField(max_length=255)
    land_area = models.CharField(max_length=255)
    landuse = models.CharField(max_length=255)
    leisure = models.CharField(max_length=255)
    man_made = models.CharField(max_length=255)
    military = models.CharField(max_length=255)
    natural = models.CharField(max_length=255)
    office = models.CharField(max_length=255)
    place = models.CharField(max_length=255)
    shop = models.CharField(max_length=255)
    sport = models.CharField(max_length=255)
    tourism = models.CharField(max_length=255)
    other_tags = models.CharField(max_length=255)
    GEOMETRY = models.MultiPolygonField()

    class Meta:
        db_table = 'multipolygons'
        managed = False

class OtherRelations(models.Model):
    ogc_fid = models.AutoField(primary_key=True, editable=False)
    osm_id = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    type = models.CharField(max_length=255)
    other_tags = models.CharField(max_length=255)
    GEOMETRY = models.GeometryCollectionField()

    class Meta:
        db_table = 'other_relations'
        managed = False

class PlacePoint(models.Model):
    ogc_fid = models.AutoField(primary_key=True, editable=False)
    osm_id = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    barrier = models.CharField(max_length=255)
    highway = models.CharField(max_length=255)
    ref = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    is_in = models.CharField(max_length=255)
    place = models.CharField(max_length=255)
    man_made = models.CharField(max_length=255)
    other_tags = models.CharField(max_length=255)
    GEOMETRY = models.PointField()

    class Meta:
        db_table = 'points'
        managed = False

map/views.py
from django.shortcuts import render, redirect
import csv, json
from .models import Property, PropertyGIS
from django.http import JsonResponse
from django.views import View
import json
from django.core.serializers import serialize
# Create your views here.
def home(request):
    """
    latlngs =  [
        {"latlngs": [[10.59, 76.45],[10.5901, 76.4503],[10.5808, 76.4501]], "id": 1},
        {"latlngs": [[10.5903, 76.4502],[10.5901, 76.4504],[10.5808, 76.4501]], "id": 2},
    ];
    """
    latlngs = [{"latlngs": p.latlngs, "id": p.id} for p in Property.objects.all()]
    return render(
        request,
        "map/home.html",
        {"f_latlogs": latlngs, 'propertygis':json.loads(serialize("geojson",PropertyGIS.objects.all()))},
    )


def save_property(request):
    if request.method == "POST":
        Property.objects.create(
            name=request.POST["name"],
            address=request.POST["address"],
            latlngs=json.loads(request.POST["latlngs"]),  # getlist("latlngs[]"),
        )
        return JsonResponse({"success": True})


class PropertyDetail(View):
    """Show Details of a Property"""
    def get(self, request, property):
        property = Property.objects.get(id= property)
        return render(request,'map/property_detail.html',{"property":property})

    def post(self, request, property):
        Property.objects.get(id= property).delete()
        return redirect('/')


from django.contrib.gis import forms
class PropertyForm(forms.ModelForm):
    class Meta:
        model = PropertyGIS
        fields = ('id', 'name','GEOMETRY')
        GEOMETRY = forms.PolygonField()


def property_insert(request):
    form = PropertyForm()
    return render(request, 'map/add.html', {'form': form})

markers/views.py
import json

from django.core.serializers import serialize
from django.views.generic.base import TemplateView

from markers.models import Lines, MultiPolygons, OtherRelations, PlacePoint, MultilineStrings


from rest_framework import viewsets
from rest_framework_gis import filters

from markers.serializers import MarkerSerializer


class MarkerViewSet(viewsets.ReadOnlyModelViewSet):
    bbox_filter_field = "GEOMETRY"
    filter_backends = (filters.InBBoxFilter,)
    queryset = MultiPolygons.objects.all()
    serializer_class = MarkerSerializer

class MarkersMapView(TemplateView):
    template_name = "map.html"

# class MarkersMapView(TemplateView):
#     template_name = "map.html"

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context["markers"] = json.loads(
#             serialize(
#                 "geojson",
#                 MultilineStrings.objects.all(),
#             )
#         )
#         return context

map/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<base target="_top">
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>Real Estate</title>

	<link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %}" />
	{% block css %}
	{% endblock %}

	{% block extra_css %}
	{% endblock %}

	<style>
		html,
		body {
			height: 100%;
			margin: 0;
		}
	</style>
</head>

<body>
	{% block body %}
	{% endblock %}


	<script src="{% static 'jquery-3.7.1.js' %}"></script>
	<script src="{% static 'bootstrap/bootstrap.bundle.min.js' %}"></script>
	{% block js %}
	{% endblock %}

	{% block extra_js %}
	{% endblock %}
</body>

</html>

map/templates/gis/custom_layers.html
{% extends "gis/openlayers-osm.html" %}
{% load l10n %}

{% block base_layer %}
var base_layer = new ol.layer.Tile({
    source: new ol.source.XYZ({
        attributions: "ARC GIS",
        url: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'
    })
});
{% endblock %}

map/templates/map/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {{ form.media }}
</head>
<body>
    <div id="map">
        <form enctype="multipart/form-data" method="post" action="">
            {% csrf_token %}
                {{ form.as_p }}
            <input type="submit" value="Submit"/>
        </form>
    </div>
</body>
</html>

map/templates/map/add_polygon_modal.html
<div class="modal fade" id="addPolygonModal" tabindex="-1" aria-labelledby="addPolygonLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="addPolygonLabel">Add my property</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form>
            <div class="mb-3">
              <label for="owner-name" class="col-form-label">Owner Name:</label>
              <input type="text" class="form-control" id="txt_name">
            </div>
            <div class="mb-3">
              <label for="address-text" class="col-form-label">Address:</label>
              <textarea class="form-control" id="txt_address"></textarea>
            </div>
            <div class="mb-3">
              <label for="position-text" class="col-form-label">Position:</label>
              <textarea class="form-control" id="txt_latlngs" disabled></textarea>
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary" id="btn_save_property">Save property</button>
        </div>
      </div>
    </div>
</div>

map/templates/map/base.html
{% extends 'base.html' %} 
{% load static %}
{% block css %} 
<link rel="stylesheet" href="{% static 'leaflet/leaflet.css' %}"/>
{% endblock %}

{% block js %} 
<script src="{% static 'leaflet/leaflet.js' %}"></script>

<script src="{% static 'leaflet/leaflet.draw/Leaflet.draw.js' %}""></script>
<script src="{% static 'leaflet/leaflet.draw/Leaflet.Draw.Event.js' %}"></script>
<link rel="stylesheet" href="{% static 'leaflet/leaflet.draw/leaflet.draw.css' %}" />

<script src="{% static 'leaflet/leaflet.draw/Toolbar.js' %}"></script>
<script src="{% static 'leaflet/leaflet.draw/Tooltip.js' %}"></script>

<script src="{% static 'leaflet/leaflet.draw/ext/GeometryUtil.js' %}"></script>
<script src="{% static 'leaflet/leaflet.draw/ext/LatLngUtil.js' %}"></script>
<script src="{% static 'leaflet/leaflet.draw/ext/LineUtil.Intersect.js' %}"></script>
<script src="{% static 'leaflet/leaflet.draw/ext/Polygon.Intersect.js' %}"></script>
<script src="{% static 'leaflet/leaflet.draw/ext/Polyline.Intersect.js' %}"></script>
<script src="{% static 'leaflet/leaflet.draw/ext/TouchEvents.js' %}"></script>

<script src="{% static 'leaflet/leaflet.draw/draw/DrawToolbar.js' %}"></script>
<script src="{% static 'leaflet/leaflet.draw/draw/handler/Draw.Feature.js' %}"></script>
<script src="{% static 'leaflet/leaflet.draw/draw/handler/Draw.SimpleShape.js' %}"></script>
<script src="{% static 'leaflet/leaflet.draw/draw/handler/Draw.Polyline.js' %}"></script>
<script src="{% static 'leaflet/leaflet.draw/draw/handler/Draw.Marker.js' %}"></script>
<script src="{% static 'leaflet/leaflet.draw/draw/handler/Draw.Circle.js' %}"></script>
<script src="{% static 'leaflet/leaflet.draw/draw/handler/Draw.CircleMarker.js' %}"></script>
<script src="{% static 'leaflet/leaflet.draw/draw/handler/Draw.Polygon.js' %}"></script>
<script src="{% static 'leaflet/leaflet.draw/draw/handler/Draw.Rectangle.js' %}"></script>
<script src="{% static 'leaflet/leaflet.draw/Control.Draw.js' %}"></script>
{% endblock %}
    

map/templates/map/home.html
{% extends 'map/base.html' %}
{% block body %}
{% include 'map/add_polygon_modal.html' %}
{{ propertygis|json_script:"markers-data" }}
<div id="map" style="width:100%; height: 100%"></div>
{% endblock %}

{% block extra_js %}
<!-- https://leaflet.github.io/Leaflet.draw/docs/leaflet-draw-latest.html#l-edit-poly -->
<script>
    const osmUrl = 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
        osmAttrib = '&copy; <a href="http://openstreetmap.org/copyright">OpenStreetMap</a> contributors',
        osm = L.tileLayer(osmUrl, { maxNativeZoom: 18, maxZoom: 20, attribution: osmAttrib }),
        map = new L.Map('map', { center: new L.LatLng(10.59, 76.45), zoom: 13 }),
        drawnItems = L.featureGroup().addTo(map);
    L.control.layers({
        'osm': osm.addTo(map),
        "google": L.tileLayer('http://www.google.cn/maps/vt?lyrs=s@189&gl=cn&x={x}&y={y}&z={z}', {
            maxNativeZoom: 18, // https://gis.stackexchange.com/a/78851
            maxZoom: 20,
            attribution: 'google'
        }),
        "arcgis": L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}', { //https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
            maxNativeZoom: 18, // https://gis.stackexchange.com/a/78851
            maxZoom: 20,
            attribution: 'arcgis'
        }),
    }, { 'drawlayer': drawnItems }, { position: 'topleft', collapsed: false }).addTo(map);

    // https://gis.stackexchange.com/a/447345
    const markers = JSON.parse(document.getElementById("markers-data").textContent);
    let feature = L.geoJSON(markers).bindPopup(function (layer) {
        const div = document.createElement("div");
        div.innerHTML = `<br>${layer.feature.properties.name}<br>`;

        const button = document.createElement("button");
        button.innerHTML = "Create Line";

        button.onclick = function() {
            alert(layer.feature.properties.pk)
        }

        div.appendChild(button);
        return div;
    }).addTo(map);
    // map.fitBounds(feature.getBounds(), {padding: [100, 100],});

    map.addControl(new L.Control.Draw({
        draw: {
            polygon: {
                allowIntersection: false,
                showArea: true
            },
            marker: false, // remove marker
            circlemarker: false, // remove
            circle: false, // remove
            rectangle: false, // remove
            polyline: false, // remove
        }
    }));

    map.on(L.Draw.Event.CREATED, function (event) {
        let layer = event.layer;
        drawnItems.addLayer(layer);
        // get co ordinates of drawn polygon
        // console.log(layer.getLatLngs())
        $("#txt_latlngs").val(layer.getLatLngs())
        $("#addPolygonModal").modal("show");
    });



    // create a red polygon from an array of LatLng points
    let latlngs = {{ f_latlogs| safe }};
    let polygon;
    for (let i = 0; i < latlngs.length; i++) {
        polygon = L.polygon(latlngs[i]["latlngs"], { color: 'red', id: latlngs[i]['id'] }).addTo(map);
        polygon.on('click', function () {
            window.open(`map/${this.options.id}/`, '_blank').focus();
        });
    }

    function latlngs_to_array(latlngs) {
        // https://stackoverflow.com/a/51379191/2351696
        // INPUT: "LatLng(17.50438, 1.04772),LatLng(17.48686, 1.05775)"            
        // OUTPUT: [['17.50438','1.04772'], ['17.48686','1.05775']]
        let splittedArray = latlngs.split("LatLng"),
            outputArray = [];

        splittedArray.forEach(o => {
            if (o) {
                let extractedLTLNG = o.match(/\(([^)]+)\)/)[1].split(",");
                let tempArray = [extractedLTLNG[0], extractedLTLNG[1]];
                outputArray.push(tempArray);
            } else {
                return;
            }
        })
        return outputArray;
    }

    $("#btn_save_property").click(function () {
        let data = {
            name: $("#txt_name").val(),
            address: $("#txt_address").val(),
            latlngs: JSON.stringify(latlngs_to_array($("#txt_latlngs").val())),
            csrfmiddlewaretoken: '{{csrf_token}}',
        }
        $.post("{% url 'map:save_property' %}", data)
            .done(function (resp) {
                location.reload();
            })
            .fail(function (xhr, textStatus, errorThrown) {
                $("#addPolygonModal").modal("hide");
            });
    });
</script>
{% endblock %}

map/templates/map/property_detail.html
{% extends 'base.html' %}
{% block body %}

<div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">{{ property.name }}</h5>
      <p class="card-text">{{ property.address }}</p>
      <form method="POST" action="{% url 'map:property_detail' property.id %}">{% csrf_token %}
        <button type="submit"  class="btn btn-primary">Delete</button>
        </form>
    </div>
  </div>

{% endblock %}

markers/templates/map.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Markers Map</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" type="text/css" href="https://unpkg.com/leaflet/dist/leaflet.css" crossorigin="" />
  <style>
    html,
    body {
      height: 100%;
      margin: 0;
    }

    #map {
      height: 100%;
      width: 100%;
    }
  </style>
</head>

<body>
  <div id="map"></div>
  <script src="https://unpkg.com/leaflet/dist/leaflet.js" crossorigin=""></script>
  <script src="{% static 'map.js' %}" defer></script>
</body>

</html>

property/templates/property/property_detail.html
{% extends 'base.html' %}
{% block body %}

<div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">{{ property.name }}</h5>
      <p class="card-text">{{ property.address }}</p>
      <form method="POST" action="{% url 'property:property_detail' property.id %}">{% csrf_token %}
        <button type="submit"  class="btn btn-primary">Delete</button>
        </form>
    </div>
  </div>

{% endblock %}